import 'modern-normalize/modern-normalize.css';
import '@/scss/globals.scss';
import React from "react";
import Head from 'next/head';
import Header from "@/components/header";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode}) {
  return (
    <html lang="en">
        <Head>
            <title>Земля у Озера</title>
        </Head>
        <body className="page">
            <Header/>
            {children}
        </body>
    </html>
  )
}
