import 'modern-normalize/modern-normalize.css';
import '@/scss/globals.scss';
import React from "react";
import Header from "@/components/header";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="page">
        <Header/>
        {children}
      </body>
    </html>
  )
}
